### PR TITLE
Detaching disks when vmgroup is removed

### PR DESCRIPTION
**Pull request by msterin**
Replaces https://github.com/vmware/docker-volume-vsphere/pull/1652
Fixes https://github.com/vmware/docker-volume-vsphere/issues/1441

Force detach disks even if we cannot find VMgroup

If VMgroup for VM is not found during detach operation
(can happen if, say _DEFAULT group was deleted when a container with an attached volume was in flight on the VM), we force_detach volume no matter what.

The code introduces special handling of get_tenant() failures on detach path. It looks for attached disk matching datastore/volume (ignoring tenant) and detaches it if found. 

See #1441 and in-code comment for more info

Basically, @govint was right and it is not trivial, but not impossible either. 

Github diff is confused, add `?w=1` to diff URL to see the changes without whitespace shift 

TEST: Manual: 
 * run a container with a volume
 * remove _DEFAULT group
 * observe the disk detached

ESX log: 
```
[root@msterin-esx-136:/usr/lib/vmware/vmdkops/bin] ./vmdkops_admin.py config init --local
Warning: this feature is EXPERIMENTAL
Creating new DB at /etc/vmware/vmdkops/auth-db
```

VM:  ` docker run -it --rm -v vol1:/vol busybox ping 8.8.8.8 > /dev/null`

ESX Log:
```
...
07/29/17 01:21:08 307165 [vDVS_test1-datastore1._DEFAULT.vol1] [INFO   ] executeRequest 'attach' completed with ret={'Unit': '0', 'ControllerPciSlotNumber': '192'}
...
```

VM: Control-C to kill to the container

ESX log: 
```
07/29/17 01:21:30 307165 [Thread-5] [WARNING] executeRequest: FORCE_DETACH vm_uuid=42190e33-70c6-f937-36ff-c7847eae3268, vm_name=vDVS_test1, full_volume_name=vol1@datastore1
07/29/17 01:21:30 307165 [Thread-5] [INFO   ] vol_name=vol1, datastore=datastore1
07/29/17 01:21:30 307165 [Thread-5] [WARNING] Failed to find VM by VC UUID 50193d94-964c-8fe0-f928-8199a1ff9561, trying BIOS UUID 42190e33-70c6-f937-36ff-c7847eae3268
07/29/17 01:21:30 307165 [Thread-5] [INFO   ] Found vm name='vDVS_test1'
...
07/29/17 01:21:30 307165 [Thread-5] [INFO   ] backing disk name is  dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk
07/29/17 01:21:30 307165 [Thread-5] [WARNING] Found path: /vmfs/volumes/datastore1/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk
07/29/17 01:21:30 307165 [vDVS_test1-datastore1.__NoSuchTenant__.vol1] [INFO   ] *** disk_detach: VMDK /vmfs/volumes/datastore1/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk to VM 'vDVS_test1' , bios uuid = 42190e33-70c6-f937-36ff-c7847eae3268, VC uuid=50193d94-964c-8fe0-f928-8199a1ff9561)
07/29/17 01:21:30 307165 [vDVS_test1-datastore1.__NoSuchTenant__.vol1] [WARNING] Failed to find VM by VC UUID 50193d94-964c-8fe0-f928-8199a1ff9561, trying BIOS UUID 42190e33-70c6-f937-36ff-c7847eae3268
07/29/17 01:21:30 307165 [vDVS_test1-datastore1.__NoSuchTenant__.vol1] [INFO   ] Found vm name='vDVS_test1'
07/29/17 01:21:31 307165 [vDVS_test1-datastore1.__NoSuchTenant__.vol1] [INFO   ] Disk detached /vmfs/volumes/datastore1/dockvols/11111111-1111-1111-1111-111111111111/vol1.vmdk
07/29/17 01:21:31 307165 [vDVS_test1-datastore1.__NoSuchTenant__.vol1] [INFO   ] executeRequest 'detach' completed with ret=None
```
 

@tusharnt @govint @lipingxue @shaominchen @pshahzeb @shuklanirdesh82

### CODE REVIEW

**Comment by shaominchen** [comment]
@govint @msterin Have we verified other volume operations (create/delete/attach/ls/inspect) when default vmgroup is removed? If detach is the only operation that needs a special handling, it's probably acceptable with this hack. Otherwise if more operations need special hacks like this, then it is a design issue.

**Comment by msterin** [comment]
@shaominchen - thanks for taking a look !
All other operations should be rejected if a VM is not in a named group and there is no fallback (default). This is by design (for security lockdown)  and is supposed to be tested outside of this PR, so the issue was with detach only. Thus the patch is explicitly dealing with the detach only.
Actually, the reasons it's a hack is not the design, but rather implementation which certainly requires refactoring and proper layering.

**Comment by msterin** [comment]
> Create a volume (within default vmgroup), then remove default vmgroup. What's the behavior for ls/inspect/attach?

the designed behavior is that this volume is not seen by any VM, unless  the default group is brought back

> Are we leaving over dirty data that user cannot clean up using regular Docker or AdminCLI commands?

all can be cleaned using regular vmkfstools, as for other operations (e.g moving a volume to a different group). All these are expected to be super rare. and vmkfstools is sufficient to accomplish them all.


>    Create a volume (within default vmgroup), attach the volume, then remove default vmgroup. What's the behavior of the running container?

By design container keeps running. When it's done and releases the volume, it is getting detached (assuming no other containers are using it). This detach was broken, this PR fixes it


> In short, we can't let users to remove the default vmgroup (even with a warning), and then leaving over a damaged or inconsistent system that users don't know how to deal with.

There is no damaged on inconsistent system in sight. If  they remove a default group, all volumes within it (as are within any other deleted group) become unavailable for further usage , until they either manually relocated or group is recreated. 


> I understand that this PR is only dealing with detach workflow only. However, I think it's better to get a clear answer for above questions before we moving ahead to apply this patch.

Please see above. I hope these answers are clear enough.

**Comment by msterin** [comment]
Thanks @shaominchen . WIl fix typos and merge (after CI pass)

**Pull request merged**
