### PR TITLE
Cli auth.liping

### PR DESCRIPTION
**Pull request by lipingxue**
This change includes the code change to enable AdminCLI command to support tenants.
See #620

### CODE REVIEW

**Comment by lipingxue** [comment]
Right now, all unit tests are done manually.

- 

 create a tenant

```

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant create --name=tenant1 --vm-list photon4

 [root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name     Description  Default_datastore  VM_list  
------------------------------------  -------  -----------  -----------------  -------  
f140cf6e-1fea-42b0-a706-41efc52d195c  tenant1               default_ds         photon4  

 [root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm ls --name=tenant1
Uuid                                  Name     
------------------------------------  -------  
564df562-3d58-c99a-e76e-e8792b77ca2d  photon4  
```

- 

 add vm to tenant
```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm add --name=tenant1 --vm-list photon5

 
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls 
Uuid                                  Name     Description  Default_datastore  VM_list          
------------------------------------  -------  -----------  -----------------  ---------------  
f140cf6e-1fea-42b0-a706-41efc52d195c  tenant1               default_ds         photon4,photon5  

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm ls --name=tenant1
Uuid                                  Name     
------------------------------------  -------  
564df562-3d58-c99a-e76e-e8792b77ca2d  photon4  
564d4728-f1c7-2029-d01e-51f5e6536cd9  photon5  
```

- remove vm from tenant

```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm rm --name=tenant1 --vm-list photon5

 [root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm ls --name=tenant1

Uuid                                  Name     
------------------------------------  -------  
564df562-3d58-c99a-e76e-e8792b77ca2d  photon4  

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name     Description  Default_datastore  VM_list  
------------------------------------  -------  -----------  -----------------  -------  
f140cf6e-1fea-42b0-a706-41efc52d195c  tenant1               default_ds         photon4  

```

-  Add access control for a (tenant,datastore)
```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access add --name=tenant1 --datastore=datastore1 --rights all --volume-maxsize=500MB --volume-totalsize=1GB

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access ls --name=tenant1
Datastore   Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
----------  -------------  -------------  ------------  ---------------  ----------  
datastore1  1              1              1             500.00MB         1.00GB      
```
- Modify access control for a (tenant,datastore)
```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access set --name=tenant1 --datastore=datastore1 --rm-rights=mount --volume-maxsize=500MB --volume-totalsize=2GB

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access ls --name=tenant1
Datastore   Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
----------  -------------  -------------  ------------  ---------------  ----------  
datastore1  1              1              0             500.00MB         2.00GB      

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access set --name=tenant1 --datastore=datastore1 --add-rights=mount --volume-maxsize=600MB --volume-totalsize=1GB

 [root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access ls --name=tenant1
Datastore   Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
----------  -------------  -------------  ------------  ---------------  ----------  
datastore1  1              1              1             600.00MB         1.00GB      
```
- Remove access control for a (tenant, datastore)
```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access rm --name=tenant1 --datastore=datastore1

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access ls --name=tenant1
Datastore  Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
---------  -------------  -------------  ------------  ---------------  ----------  
```

**Comment by lipingxue** [comment]
create two tenants, make sure each tenant can only see volumes belong to that tenant

step 1: create another tenant(tenant2), add vm and access control to this tenant
```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant create --name=tenant2 --vm-list=photon5

 [root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name     Description  Default_datastore  VM_list  
------------------------------------  -------  -----------  -----------------  -------  
f140cf6e-1fea-42b0-a706-41efc52d195c  tenant1               default_ds         photon4  
98958c5c-ae85-4a59-8e86-6845b107158c  tenant2               default_ds         photon5  

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access add --name=tenant2 --datastore=datastore1 --rights all --volume-maxsize=1GB --volume-totalsize=2TB

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name     Description  Default_datastore  VM_list  
------------------------------------  -------  -----------  -----------------  -------  
f140cf6e-1fea-42b0-a706-41efc52d195c  tenant1               default_ds         photon4  
98958c5c-ae85-4a59-8e86-6845b107158c  tenant2               default_ds         photon5  

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access ls --name=tenant1
Datastore   Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
----------  -------------  -------------  ------------  ---------------  ----------  
datastore1  1              1              1             600.00MB         1.00GB      

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access ls --name=tenant2
Datastore   Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
----------  -------------  -------------  ------------  ---------------  ----------  
datastore1  1              1              1             1.00GB           2.00TB      
``` 
step 2: create two volumes on photon4 (VM which is associated to tenant1)
```
 root@photon-JQQBWNwG6 [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
root@photon-JQQBWNwG6 [ ~ ]# docker volume create --driver=vmdk --name=tenant1-vol1 -o size=100MB
tenant1-vol1
root@photon-JQQBWNwG6 [ ~ ]# docker volume create --driver=vmdk --name=tenant1-vol2 -o size=100MB
tenant1-vol2
```
step 3: create two volumes on photon 5 (VM which is associated to tenant2)
```
root@photon-eZ5ILvREQ [ ~ ]# docker volume ls
DRIVER              VOLUME NAME

root@photon-eZ5ILvREQ [ ~ ]# docker volume create --driver=vmdk --name=tenant2-vol1 -o size=200MB
tenant2-vol1
root@photon-eZ5ILvREQ [ ~ ]# docker volume create --driver=vmdk --name=tenant2-vol2 -o size=200MB
tenant2-vol2
```

step4:  run “docker volume ls” on both VMs, only volumes created by that tenant are listed
On photon4 (tenant1)
```
root@photon-JQQBWNwG6 [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                tenant1-vol1
vmdk                tenant1-vol2
```
On photon 5(tenant2)
```
root@photon-eZ5ILvREQ [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                tenant2-vol1
vmdk                tenant2-vol2
```

**Comment by lipingxue** [comment]
unit test for tenant rm  command

step 1: remove tenant2
```
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant rm --name=tenant2 --remove-volumes=True
 [root@localhost:~] 

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name     Description  Default_datastore  VM_list  
------------------------------------  -------  -----------  -----------------  -------  
f140cf6e-1fea-42b0-a706-41efc52d195c  tenant1               default_ds         photon4 
 ```

step 2: run "docker volume ls" on photon5 (which used to belong to tenant2, but now not belong to any tenant), it will only show volumes which not associated with any tenant
```
root@photon-eZ5ILvREQ [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                non-tenant-vol1
vmdk                non-tenant-vol2
vmdk                non-tenant-vol3

```

step 3: check the "/vmfs/volumes/datastore1/dockervols/", all volumes under "tenant2" are removed and directory "tenant2" is removed

**Comment by lipingxue** [comment]
unit test for ls command with --tenant option

```


[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls 
Volume           Datastore   Created By VM  Created                   Attached To VM  Policy  Capacity  Used     Filesystem Type  Access      Attach As               
---------------  ----------  -------------  ------------------------  --------------  ------  --------  -------  ---------------  ----------  ----------------------  
non-tenant-vol1  datastore1  photon4        Sun Aug 14 09:36:45 2016  detached        N/A     100.00MB  0B       ext4             read-write  independent_persistent  
non-tenant-vol2  datastore1  photon4        Sun Aug 14 09:40:53 2016  detached        N/A     100.00MB  0B       ext4             read-write  independent_persistent  
non-tenant-vol3  datastore1  photon4        Thu Aug 18 07:22:24 2016  detached        N/A     100.00MB  13.00MB  ext4             read-write  independent_persistent  
tenant1-vol1     datastore1  photon4        Fri Aug 19 16:13:03 2016  detached        N/A     100.00MB  13.00MB  ext4             read-write  independent_persistent  
tenant1-vol2     datastore1  photon4        Fri Aug 19 16:13:11 2016  detached        N/A     100.00MB  13.00MB  ext4             read-write  independent_persistent  

 [root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls -c=volume,datastore,access
Volume           Datastore   Access      
---------------  ----------  ----------  
non-tenant-vol1  datastore1  read-write  
non-tenant-vol2  datastore1  read-write  
non-tenant-vol3  datastore1  read-write  
tenant1-vol1     datastore1  read-write  
tenant1-vol2     datastore1  read-write  

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls --tenant=tenant1
Volume        Datastore   Created By VM  Created                   Attached To VM  Policy  Capacity  Used     Filesystem Type  Access      Attach As               
------------  ----------  -------------  ------------------------  --------------  ------  --------  -------  ---------------  ----------  ----------------------  
tenant1-vol1  datastore1  photon4        Fri Aug 19 16:13:03 2016  detached        N/A     100.00MB  13.00MB  ext4             read-write  independent_persistent  
tenant1-vol2  datastore1  photon4        Fri Aug 19 16:13:11 2016  detached        N/A     100.00MB  13.00MB  ext4             read-write  independent_persistent  

[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls --tenant=tenant1 -c=volume,datastore,access
Volume        Datastore   Access      
------------  ----------  ----------  
tenant1-vol1  datastore1  read-write  
tenant1-vol2  datastore1  read-write  
```

**Comment by lipingxue** [comment]
Please start a first round review.

**Comment by msterin** [comment]
@lipingxue - please rebase on master (which now has the CLI syntax merged) and re-push , this way we can review the delta only. Thanks

**Comment by lipingxue** [comment]
@msterin  I have rebased with master and repush the change.

**Comment by msterin** [comment]
Overall good draft and the logic is sound. Copy-n-paste should be eliminated and some consistency in messages (with the rest of the code) is needed. Also it still has a bunch of files from prior PRs, there is no need to do it - please only push the new code in this PR (you can always branch from the prior PR , this way only delta will show up on the review)

**Comment by lipingxue** [comment]
I incorrectly merged commit(SHA 396dec8) into master branch. This merge has been revert from master by Ritesh.

**Pull request merged**
