### PR TITLE
[WIP] Decrement reference count on error in plugin Mount().

### PR DESCRIPTION
**Pull request by govint**
Modified Mount() to decrement volume ref count on error. Mount() already derements ref count in one code path and in another doesn't (within Mount()).

This change is still missing one update - how do we want to handle pre Docker 1.13-0-rc1?

a. Check for Docker version < 1.13.0 - this may be redundant code over time and its expecting a certain behavior thats not documented and a bug in Docker - plugin Unmount() is called even on Mount() error.

b. Always decrement ref count in Unmount() and if less than or equal to zero then set ref count to 0 and unmount the volume.

Please comment which way we want to go with this (b) seems ok.

### CODE REVIEW

**Comment by govint** [comment]
Fixes #608

**Comment by kerneltime** [comment]
This change cannot be merged till we do not address the pre Docker 1.13 installs.

**Comment by kerneltime** [comment]
Does the ref count below zero guarantee that there is no mount? I cannot see a scenario where ref count is below zero but the volume is still being accessed. I am fine with b.

**Comment by kerneltime** [comment]
We should move this to https://github.com/vmware/docker-volume-vsphere/issues/608 where can finalize on options.

**Pull request closed without merging**
