### PR TITLE
Add support for RHEL

### PR DESCRIPTION
**Pull request by kerneltime**
This adds support for both Photon and RHEL in the same rpm binary. 
Dropped dependency check for docker for rpm to make the same binary work for RHEL and Photon.

CI system currently tests for regression, support for RHEL in CI is part of a separate PR.

Testing:

Single RHEL 7.2 VM with docker 1.12

1. Uninstalled docker, plugin installs on FS but does not start up.
2. Install docker and restart plugin, the plugin works fine.
3. Ran manual tests after deploy-vm on Photon and RHEL (create, multiple attaches)

### CODE REVIEW

**Comment by msterin** [comment]
LGTM. One question though - are we going to have these checked in CI ?

**Comment by kerneltime** [comment]
Yes. Not this PR though.

**Comment by govint** [comment]
Can we also ensure no pvscsi controllers in the VM to start with. And each CI run should start the VM without a PVSCSI controller. We have sufficient code thats never tested when a pvscsi controller is already present.

**Comment by msterin** [comment]
The code is tested every time anyone bring up a new docker vm, which is reasonable often. And are you talking about having it tested in CI (which is planned and issue # is mentioned above) or about something else ?

**Comment by govint** [comment]
When developing fixes, the same VM is used for all development and test. And that VM invariably has the pvscsi controller in it (from local testing). The CI VMs should be a fresh slate without any configuration that's also created by the plugin, so any issue will be caught before a fix is merged.

**Comment by msterin** [comment]
@govint , we should take the comments about pvscsi out of RHEL fix thread.

**Comment by kerneltime** [comment]
@msterin Agreed. We should file a ticker for missing test cases. The problem is dual sided on one had we want machines that have been running/upgraded over a long period and we want to replicate the fresh install use case. This sounds more like a use case for missing tests in CI.

**Comment by kerneltime** [comment]
Using https://github.com/vmware/docker-volume-vsphere/pull/584 to capture the need for fresh VMs as part of CI.

**Comment by pdhamdhere** [comment]
LGTM

**Pull request merged**
