### PR TITLE
Pass the kill switch into docker and nested Makefiles.

### PR DESCRIPTION
**Pull request by kerneltime**
The kill switch is to avoid UI code from being built and packaged
by default. This kill switch will be in place till UI is ready to
be consumed. Once the UI code is ready and integrated with the
VMODL APIs, the kill switch can be removed.

### CODE REVIEW

**Comment by shaominchen** [comment]
The change looks straightforward, but can you add some description about the kill switch? Just for tracking purposes.

**Comment by kerneltime** [comment]
Done, the commit is updated.

**Comment by shaominchen** [comment]
LGTM.

**Comment by msterin** [comment]
Please add something about "In order to enable the UI build, do <this and that>".
Other than that LGTM

**Comment by kerneltime** [comment]
It was documented in the PR that introduced the kill switch (which stopped UI from building).
To build UI run:
```
INCLUDE_UI=true make
```
If this lands up being a permanent feature will add documentation in the relevant build instructions.

**Pull request merged**
