### PR TITLE
reordering revert snapshot recovery (Addressing #888)

### PR DESCRIPTION
**Pull request by shuklanirdesh82**
Addressing issue reported at #888

I have seen that vm on 6.5 is always having issue as setup script exits the moment ESX IP is reachable and VM on the same host are yet to honor IP.

Proposing the solution for the problem reported using following run. If the issue persists then we should retry logic for vm IP.

From https://ci.vmware.run/vmware/docker-volume-vsphere/1061
```
Resetting testbed
Waiting for revert to complete
ESX 6.0
192.168.31.19
ESX 6.5
192.168.31.62
Reset complete
$ GOVC_USERNAME=$GOVC_USERNAME_ESX
$ GOVC_PASSWORD=$GOVC_PASSWORD_ESX
$ if [ "$TAG" != "" ]; then export PKG_VERSION=$TAG; fi
$ 
$ echo "=> Running tests on ESX_6.5" `date` > /dev/null
$ 
$ export GOVC_URL=$GOVC_URL_6_5
$ export VM1=`$GOVC_GET_IP photon.vmfs`
govc: Post https://192.168.31.62/sdk: net/http: TLS handshake timeout
$ export VM2=`$GOVC_GET_IP Ubuntu.16.10`
$ ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL_6_5 $VM1 $VM2 1061 < /dev/null


=> truncate vm logs Thu Feb 2 22:17:23 UTC 2017




=> truncate esx logs Thu Feb 2 22:17:23 UTC 2017




=> starting deploy and test Thu Feb 2 22:17:24 UTC 2017


Removing auth DB file at 192.168.31.62:'/etc/vmware/vmdkops/auth-db'


=> Cleaning up on ESX 192.168.31.62 Thu Feb 2 22:17:25 UTC 2017


Removal Result:
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: 
   VIBs Removed: VMWare_bootbank_esx-vmdkops-service_0.10.fb31b27-0.0.1
   VIBs Skipped: 


=> Deploying to ESX root@192.168.31.62 Thu Feb 2 22:17:46 UTC 2017


Installation Result:
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: VMWare_bootbank_esx-vmdkops-service_0.11.68b8157-0.0.1
   VIBs Removed: 
   VIBs Skipped: 
vmdkops-opsd is running pid=552854


=> setupVMType: Unsupported VM Type root@1061 Thu Feb 2 22:18:16 UTC 2017


make[1]: *** [clean-vm] Error 1
make: *** [deploy-vm] Error 2


=> Build + Test not successful Thu Feb 2 22:18:16 UTC 2017
```

### CODE REVIEW

**Comment by pdhamdhere** [comment]
@kerneltime Are you okay with change. Looks reasonable to me.

**Comment by kerneltime** [comment]
Why not add the wait for VM IP to be available?

**Comment by shuklanirdesh82** [comment]
> Why not add the wait for VM IP to be available?

It seems the root cause is ```govc: Post https://192.168.31.62/sdk: net/http: TLS handshake timeout``` so proposed the quick fix by reordering and mentioned in the description that If the issue persists then we should add retry logic for vm IP.

**Comment by kerneltime** [comment]
Yup we should add a retry loop.

**Pull request merged**
