### PR TITLE
Refreshing ESX 6.5 support on CI

### PR DESCRIPTION
**Pull request by shuklanirdesh82**
CI is refreshed to unblock #859.

- Drone secretes are refreshed with this PR
- one of the test is failing and needs further triage as the Ubuntu VMs are having latest docker  i.e. ```1.13``` (https://ci.vmware.run/vmware/docker-volume-vsphere/1016)

TestConcurrency is commented out to take further triage.

```
=== RUN   TestConcurrency
Running concurrent tests on tcp://192.168.31.187:2375 and tcp://192.168.31.83:2375 (may take a while)...
Running create/delete concurrent test...
--- FAIL: TestConcurrency (29.75s)
	sanity_test.go:199: Successfully connected to tcp://192.168.31.187:2375
	sanity_test.go:199: Successfully connected to tcp://192.168.31.83:2375
	sanity_test.go:298: Create/delete concurrent test failed, err: Error response from daemon: create volTestP10: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=44 with Body length 0
FAIL
```

vmdk_ops log

```
01/27/17 12:47:23 558076 [Ubuntu.14.04-[vsanDatastore] dockvols/4af40ea9-ae91-4556-b6b6-641b72c85ec5/volTestP10.vmdk] [WARNING] vmci_reply returned error Broken pipe (errno=32)
01/27/17 12:47:25 558076 [photon.vsan-[vsanDatastore] dockvols/4af40ea9-ae91-4556-b6b6-641b72c85ec5/volTestP00.vmdk] [INFO   ] executeRequest 'remove' completed with ret=None
01/27/17 12:47:25 558076 [Thread-39] [INFO   ] cmd get with opts {} on tenant_uuid 4af40ea9-ae91-4556-b6b6-641b72c85ec5 datastore vsanDatastore is allowed to execute
01/27/17 12:47:25 558076 [photon.vsan-[vsanDatastore] dockvols/4af40ea9-ae91-4556-b6b6-641b72c85ec5/volTestP01.vmdk] [INFO   ] executeRequest 'get' completed with ret={'Error': 'Volume volTestP01 not found (file: /vmfs/volumes/vsanDatastore/dockvols/4af40ea9-ae91-4556-b6b6-641b72c85ec5/volTestP01.vmdk)'}

```

//CC @shaominchen

### CODE REVIEW

**Comment by shaominchen** [comment]
@shuklanirdesh82 Do you plan to check in this change first, and investigate the TestConcurrency failure separately?

**Comment by shuklanirdesh82** [comment]
Yeah @shaominchen that's the plan, the failure is observed only against 1.13 docker and will open the separate issue later on. After getting approval you can get the change and resume your testing.

The CI changes are ready for you to test out your change.

FYI: The failure observed with my proposed change is different and expected.

**Comment by shaominchen** [comment]
@shuklanirdesh82 As I talked to you offline, I've already finished all my tests on both 6.5 and 6.0U2 setups. But until new CI is ready, I can't merge my change because it will fail in the current CI.

So, I don't need to test out my change - everything is done. Just need the new CI ready so that I can merge my PR.

**Comment by kerneltime** [comment]
Feel free to merge but link the issue where track uncommenting the tests commented here.

**Comment by shuklanirdesh82** [comment]
Thanks @kerneltime for the approval, reference has been raised to uncomment.

**Pull request merged**
