### PR TITLE
Fix test cleanup for test-esx target

### PR DESCRIPTION
**Pull request by ashahi1**
This PR addresses the issue #1479 

Performed local testing. All tests passed successfully and there were no leftover volumes
```
=> Running target test-esx Mon Oct 9 11:28:37 PDT 2017

Esx cli volume ls:

[root@sc2-rdops-vm03-dhcp-106-33:~] esxcli storage guestvol volume ls
Volume  Datastore  VMGroup  Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access  Attach-as  Created By  Created Date
------  ---------  -------  --------  ----  ----------  ------  -----------  -----------  ------  ---------  ----------  ------------

[root@sc2-rdops-vm03-dhcp-106-33:~]
```

### CODE REVIEW

**Comment by ashahi1** [comment]
@shuklanirdesh82 I have updated the test inline comments.

**Comment by shuklanirdesh82** [comment]
@ashahi1 Please take a look at CI failure and repush if needed, let's merge after having CI green with this PR.

**Comment by ashahi1** [comment]
@shuklanirdesh82 Hit the issue #1869 
```
CRITICAL:root:Traceback (most recent call last):
   File "/bin/esxcli", line 53, in <module>
    from vmware.esxcli.Session import Session, SessionOptions, IsInVisor, \
 ImportError: No module named esxcli.Session

----------------------------------------------------------------------
FAIL: vmlistener_test.go:272: VMListenerTestParams.TestFailoverAcrossVmOnVsan

vmlistener_test.go:340:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420440900), Stderr:[]uint8(nil)} ("exit status 1")
... CRITICAL:root:Exception:No module named esxcli.Session
CRITICAL:root:Traceback (most recent call last):
   File "/bin/esxcli", line 53, in <module>
    from vmware.esxcli.Session import Session, SessionOptions, IsInVisor, \
 ImportError: No module named esxcli.Session
```

**Comment by ashahi1** [comment]
CI is green against latest commit. Merging changes to master.

**Pull request merged**
