### PR TITLE
Fix to recnt_test.sh to select line for recovery tests.

### PR DESCRIPTION
**Pull request by govint**
Search for specific line in plugin log for recovery test.

Fixes https://github.com/vmware/docker-volume-vsphere/issues/790

### CODE REVIEW

**Comment by kerneltime** [comment]
This does not fix the issue https://ci.vmware.run/vmware/docker-volume-vsphere/588

**Comment by govint** [comment]
Ok, the issue is as analysed, I may have added the wrong string to search
for. Would be great to have the plugin logs.

**Comment by kerneltime** [comment]
I have attached the logs to the issue also https://ci.vmware.run/vmware/docker-volume-vsphere/590

**Comment by kerneltime** [comment]
Relevant bit from https://ci.vmware.run/vmware/docker-volume-vsphere/590 post plugin restart.
```
2016-12-02 18:26:02.31535609 +0000 UTC [INFO] No config file found. Using defaults.
2016-12-02 18:26:02.315397129 +0000 UTC [INFO] Docker VMDK plugin started config="/etc/docker-volume-vsphere.conf" version="VMDK Volume Driver v0.3" port=1019 mock_esx=false log_level=info 
2016-12-02 18:26:02.318377301 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock
2016-12-02 18:28:29.082017235 +0000 UTC [INFO] Discovered 1 volumes in use.
2016-12-02 18:28:29.082073709 +0000 UTC [INFO] Volume name=refCountTestVol count=4 mounted=true device='/dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0'
```

**Comment by govint** [comment]
Refcount will be 4 because an unmount is tried and that will fail after decrementing the refcount once.

**Comment by govint** [comment]
1. The test itself runs a container to check number of files on the refcount volume, which logs "Unmount...." logs - fixed by searching explicitly for "mounted=true"

2. Changed container command to sleep for a timeout of 3 minutes (earlier 1) so we should have all five containers running still when the plugin restarts.

**Comment by msterin** [comment]
While it's hard to belive that it take more than a minute for the test to complete (I think the issue is different from simple timing)., this was a quick-and-dirty test (my bad) and it gives us a lot of grief. bandaid does not seem to be working properly. IMO the right way would be to interrogate the plugin for the value (e.g.over a listening unix socket)  - screen scraping will  keep giving us grief. It is a larger fix, but it will really fix the test.

**Comment by govint** [comment]
This is from the log, from the first mount till the plugin restarts and
figures the number of containers using the volume.

2016-12-02 07:20:05.395801635 +0000 UTC [INFO] Mounting volume
name=refCountTestVol    <----------- first mount

2016-12-02 07:20:08.966202091 +0000 UTC [INFO] Attach complete
event="/dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0": 0x100 == IN_CREATE
name=refCountTestVol
2016-12-02 07:20:10.709604134 +0000 UTC [INFO] Mounting volume
name=refCountTestVol
2016-12-02 07:20:10.709652346 +0000 UTC [INFO] Already mounted, skipping
mount. name=refCountTestVol refcount=2
2016-12-02 07:20:10.971466326 +0000 UTC [INFO] Mounting volume
name=refCountTestVol
2016-12-02 07:20:10.971493748 +0000 UTC [INFO] Already mounted, skipping
mount. name=refCountTestVol refcount=3
2016-12-02 07:20:11.149668846 +0000 UTC [INFO] Mounting volume
name=refCountTestVol
2016-12-02 07:20:11.14969609 +0000 UTC [INFO] Already mounted, skipping
mount. name=refCountTestVol refcount=4
2016-12-02 07:20:11.332479343 +0000 UTC [INFO] Mounting volume
name=refCountTestVol
2016-12-02 07:20:11.332506087 +0000 UTC [INFO] Already mounted, skipping
mount. refcount=5 name=refCountTestVol
2016-12-02 07:20:12.550758257 +0000 UTC [INFO] Mounting volume
name=refCountTestVol

2016-12-02 07:20:12.550783947 +0000 UTC [INFO] Already mounted, skipping
mount. name=refCountTestVol refcount=6 <---- container started to figure
count of files on the test volume

2016-12-02 07:20:12.677462758 +0000 UTC [INFO] Unmounting Volume
name=refCountTestVol
2016-12-02 07:20:12.677494154 +0000 UTC [INFO] Still in use, skipping
unmount request. name=refCountTestVol refcount=5
2016-12-02 07:20:13.043050206 +0000 UTC [INFO] No config file found. Using
defaults.
2016-12-02 07:20:13.043125934 +0000 UTC [INFO] Docker VMDK plugin started
log_level=info config="/etc/docker-volume-vsphere.conf" version="VMDK
Volume Driver v0.3" port=1019 mock_esx=false
2016-12-02 07:20:13.043168132 +0000 UTC [INFO] Getting volume data from
unix:///var/run/docker.sock

2016-12-02 07:22:39.816035959 +0000 UTC [INFO] Discovered 1 volumes in use.
<--------------- Plugin completes checking volumes in use (which is beyond
the one minute timeout per container)

2016-12-02 07:22:39.816485047 +0000 UTC [INFO] Volume name=refCountTestVol
count=4 mounted=true
device='/dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0'

@msterin, can you elaborate on the change your proposing.

**Comment by kerneltime** [comment]
Were you able to reproduce the issue with docker 1.12.x and did this fix help?

**Comment by govint** [comment]
This issue will happen irrespective of the docker version. Its just looking at the plugin logs to figure if the test works ok.

**Comment by kerneltime** [comment]
Merged but this does not close #791

**Pull request merged**
