### PR TITLE
Fixes to mock-esx mode of plugin

### PR DESCRIPTION
**Pull request by govint**
Fixed mock-esx mode:

1. Allow refcounts in mock mode.
2. Get() method in mock-driver must return status depending on whether file is there or not vs. returning OK always.
3. Check for mock mode in plugin.go:mountVolume() and mount the device returned by the mock driver without calling fs.GetDevicePath().

Tests:
Ran create, rm, run, inspect tests with the plugin in mock mode.

sudo /usr/local/bin/docker-volume-vsphere -port 1019 --mock_esx=True --log_level=debug&

$ docker volume create -d vmdk --name mockvol-5
$ sudo ls -l /dev/loop*
brw-rw---- 1 root disk  7,    0 Jul 13 05:27 /dev/loop0
brw-rw---- 1 root disk  7,    1 Jul 13 05:27 /dev/loop1
brw-rw---- 1 root disk  7, 1001 Jul 18 03:30 /dev/loop1001
brw-rw---- 1 root disk  7, 1002 Jul 18 03:28 /dev/loop1002
brw-rw---- 1 root disk  7, 1003 Jul 18 03:42 /dev/loop1003
brw-r--r-- 1 root root  7, 1004 Jul 18 03:59 /dev/loop1004
brw-r--r-- 1 root root  7, 1005 Jul 18 04:13 /dev/loop1005
brw-rw---- 1 root disk  7,    2 Jul 13 05:27 /dev/loop2
brw-rw---- 1 root disk  7,    3 Jul 13 05:27 /dev/loop3
brw-rw---- 1 root disk  7,    4 Jul 13 05:27 /dev/loop4
brw-rw---- 1 root disk  7,    5 Jul 13 05:27 /dev/loop5
brw-rw---- 1 root disk  7,    6 Jul 13 05:27 /dev/loop6
brw-rw---- 1 root disk  7,    7 Jul 13 05:27 /dev/loop7
crw------- 1 root root 10,  237 Jul 13 05:27 /dev/loop-control

$ docker run --rm -it -v mockvol-5:/mnt/myvol busybox
/ # ls
bin   dev   etc   home  mnt   proc  root  sys   tmp   usr   var
/ #

$ docker volume inspect mockvol-5
[
    {
        "Name": "mockvol-5",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/mockvol-5",
        "Labels": {},
        "Scope": "local"
    }
]

$ docker volume rm mockvol-5
Detaching loopback device /dev/loop1005
mockvol-5
$ sudo ls -l /dev/loop*
brw-rw---- 1 root disk  7,    0 Jul 13 05:27 /dev/loop0
brw-rw---- 1 root disk  7,    1 Jul 13 05:27 /dev/loop1
brw-rw---- 1 root disk  7, 1001 Jul 18 03:30 /dev/loop1001
brw-rw---- 1 root disk  7, 1002 Jul 18 03:28 /dev/loop1002
brw-rw---- 1 root disk  7, 1003 Jul 18 03:42 /dev/loop1003
brw-r--r-- 1 root root  7, 1004 Jul 18 03:59 /dev/loop1004
brw-rw---- 1 root disk  7,    2 Jul 13 05:27 /dev/loop2
brw-rw---- 1 root disk  7,    3 Jul 13 05:27 /dev/loop3
brw-rw---- 1 root disk  7,    4 Jul 13 05:27 /dev/loop4
brw-rw---- 1 root disk  7,    5 Jul 13 05:27 /dev/loop5
brw-rw---- 1 root disk  7,    6 Jul 13 05:27 /dev/loop6
brw-rw---- 1 root disk  7,    7 Jul 13 05:27 /dev/loop7
crw------- 1 root root 10,  237 Jul 13 05:27 /dev/loop-control

### CODE REVIEW

**Comment by andrewjstone** [comment]
Code looks good and it mostly works. One thing that is incorrect though: ls attaches the pid of the plugin to the volume name in `docker volume ls`

```
ajs@ajs-virtual-machine:~$ ps -ef | grep 3259
root       3259   3258  0 13:19 pts/2    00:00:00 /usr/local/bin/docker-volume-vsphere -port 1019 --mock_esx
ajs        3522   3324  0 13:25 pts/8    00:00:00 grep --color=auto 3259
```

```
ajs@ajs-virtual-machine:~$ docker volume ls
vmdk                myvol-3259
```

**Comment by govint** [comment]
Ah! good one. Will fix this up.

**Comment by govint** [comment]
Fixed volumes location as /tmp/docker-volumes/<plugin-pid>/.

**Comment by andrewjstone** [comment]
LGTM

**Pull request merged**
