### PR TITLE
Kubernetes Documentation Cleanup

### PR DESCRIPTION
**Pull request by divyenpatel**
Issue: vmware/kubernetes#226

Removed unwanted tags from the YAML in kubernetes-volumes.md
Removed duplicated kubernetes/advanced.md file. 
Updated storageclass.md and clarified about VSAN Storage Capability Parameters

Commit to review: https://github.com/divyenpatel/docker-volume-vsphere/commit/c6766ae731250ac24af3aa584d026cf31f2fd5c0

Please review @luomiao @rohitjogvmw @BaluDontu @tusharnt

### CODE REVIEW

**Comment by rohitjogvmw** [comment]
LGTM

**Comment by BaluDontu** [comment]
The new commit looks good to me. LGTM!

**Comment by luomiao** [comment]
LGTM

**Comment by divyenpatel** [comment]
@tusharnt Can you merge this PR?

**Pull request merged**
