### PR TITLE
[Trivial] Increasing go test run default timeout to avoid intermittent failure of TestVolumeProperties

### LINKED ISSUE #1078: Increase default timeout parameter while running E2E tests
e2e-dkrVolDriver-test is taking more time and exceeds go test framework due to CI VMs slowness .. our objective is not to fail test due to test framework limitation.

#1057 is raised to root caused the test run slowness and this issue is to increase time out value.

It is highly possible the failure is ignored and hard to catch when the regression is introduced.

https://ci.vmware.run/vmware/docker-volume-vsphere/1788
https://ci.vmware.run/vmware/docker-volume-vsphere/1741

Sample failure
```
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/vmware/docker-volume-vsphere/vmdk_plugin/E2E_Tests	600.004s
make[1]: *** [e2e-dkrVolDriver-test] Error 1
make: *** [e2e-dkrVolDriver-test] Error 2
```

/cc @govint @msterin @pdhamdhere

### PR DESCRIPTION
**Pull request by shuklanirdesh82**
Increasing go test run default timeout to avoid intermittent failure of TestVolumeProperties

fixes #1078

/cc @govint @pdhamdhere

### CODE REVIEW

**Comment by msterin** [comment]
Do we know the root cause for the failures ? If yes - what is the Issue # ? If no - please file an issue and then this patch is LGTM

**Comment by shuklanirdesh82** [comment]
> Do we know the root cause for the failures ? If yes - what is the Issue # ? If no - please file an issue 

Thanks @msterin, I will raise an issue first.

**Comment by msterin** [comment]
>...I will raise an issue first.

ok. Please add the issue # to this PR description and it's good to go

**Comment by shuklanirdesh82** [comment]
> ok. Please add the issue # to this PR description and it's good to go

It is already added as part of description. it's #1078

**Comment by shuklanirdesh82** [comment]
> 10minutes is already long enough. We should fix testbed issues or minimize running tests.

Makes sense. Testbed cleanup and improvement is done. Closing this PR and issue as ```wontfix``` if we see more occurrences then bring back this change for the review.

**Pull request closed without merging**
