### PR TITLE
make TestVolumeCreationFirstTime data driven to run against both vms on we use on CI

### LINKED ISSUE #1017: Run the test against both of the test VMs we use now
currently CI is failing while running ```TestVolumeCreationFirstTime``` against photon vm and there is a need to check on ubuntu vm (another vm) find out the root cause. 

Since the 2 vms we use are Photon and Ubuntu, this change 
will make sure we test vs both distros, not Photon only  (as now) 

//CC @govint

### PR DESCRIPTION
**Pull request by shuklanirdesh82**
fixes #1017 ( https://ci.vmware.run/vmware/docker-volume-vsphere/1590)

Adding support to run against both vms we use for testing.

Local run output:
```
=> Running target e2e-test Thu Mar 9 17:36:05 PST 2017

../misc/scripts/build.sh e2e-dkrVolDriver-test "10.20.105.97" "10.20.105.102" "10.20.104.59"
make: Entering directory `/go/src/github.com/vmware/docker-volume-vsphere/vmdk_plugin'

=> Running target e2e-dkrVolDriver-test Fri Mar 10 01:36:06 UTC 2017

GO15VENDOREXPERIMENT=1 go test github.com/vmware/docker-volume-vsphere/vmdk_plugin/E2E_Tests -cover -v
=== RUN   TestVolumeCreationFirstTime

creating volume [abc_1489109767] on VM[10.20.105.102]
destroying volume [abc_1489109767]
creating volume [abc_1489109774] on VM[10.20.104.59]
destroying volume [abc_1489109774]--- PASS: TestVolumeCreationFirstTime (15.43s)
	createVolume_test.go:63: 
		Testcase passed: successfully able to create volume [abc_1489109767
		]
	createVolume_test.go:63: 
		Testcase passed: successfully able to create volume [abc_1489109774
		]
```

//CC @govint

### CODE REVIEW

**Comment by pshahzeb** [comment]
Just confirming about running it against photon VM since #1017 description talks about failing against photon VMs

**Comment by msterin** [comment]
There is nothing in the change about specifically "ubunbtu" VM. It looks like the change content is 
```
Run the test against both of the test VMs we use now.  

Since the 2 vms we use are Photon and Ubuntu, this change  will make sure we test vs both distros, not Photon only  (as now) 
```

is it right ? Can you please fix the commit message and PR ? 

Other than that, LGTM

**Comment by shuklanirdesh82** [comment]
> https://github.com/vmware/docker-volume-vsphere/pull/1018#issuecomment-285813200
@pshahzeb the idea behind this PR was to run against ubuntu vm as well.

**Comment by shuklanirdesh82** [comment]
> https://github.com/vmware/docker-volume-vsphere/pull/1018#issuecomment-285819102

@msterin  Thanks Mark for the suggestion! totally makes sense and more intuitive. I will update the commit message before submitting the PR.

**Pull request merged**
