### PR TITLE
Support Capabilities and report scope for volume plugin.

### PR DESCRIPTION
**Pull request by govint**
Supported a client side method to report plugin scope for Docker 1.12. Returns global scope always. Updated to current go-plugin-helpers that supports the Capabilities() method.

Testing:
1. Ran create/inspect to verify that we report global scope.
$ docker volume create -d vmdk --name clonevol_5
clonevol_5

$ docker volume inspect clonevol_5
[
    {
        "Name": "clonevol_5",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/clonevol_5",
        "Labels": {},
        "Scope": "global"
    }
]

### CODE REVIEW

**Comment by govint** [comment]
CI is pending.

**Comment by pdhamdhere** [comment]
Govindan, Should you be first submitting changes to github.com/docker/go-plugins-helpers rather than changing in vmware/docker-volume-vsphere repository?

Change in vmdk_plugin/plugin.go LGTM. Did you do any testing with swarm to see how "global" scope is used?

**Comment by kerneltime** [comment]
Test: Does our plugin continue to work with an older version of Docker?

**Comment by govint** [comment]
Prashant, no this is the current go-plugin-helpers that needs to be updated
in our repo.

**Comment by govint** [comment]
Ritesh,
   The updated plugin-helpers works fine wiith 1.11

**Comment by govint** [comment]
CI i failing with a "docker not reachable error". From test logs don't observe any errors. Plus docker version used in CI is < 1.12 and the new code (Capabilities()) isn't invoked either.

**Comment by pdhamdhere** [comment]
LGTM. Merge away once you get a green CI run.

**Comment by andrewjstone** [comment]
LGTM

**Comment by msterin** [comment]
The fix looks good.
Please separate helpers update from the code update into separate commits - they can stay within the same PR, so no need for new PRa.
LGTM after that, pending green CI

**Comment by kerneltime** [comment]
Did you rebase to master and try? I am able to push changes and CI passes.

**Pull request merged**
