### PR TITLE
[rfc] Add more context to volume locks

### LINKED ISSUE #758: Volume lockname need more context
Currently locknames are the volume name without any other context, like path, datastore or tenant.
Which makes possible to have one or more threads unnecessarily waiting for the same lock while trying to perform ops for different volumes with the same name (eg. volumes on different tenants).

This can be easily addressed giving more context to locknames using more unique names:

- Volume datastore path: "[datastorename] dockvols/tenant?/volname.vmk"
- Full volume path: "/vmfs/volumes/datastorename/ dockvols/tenant?/volname.vmk"

I think the first approach better for being more compact. (we use the lockname in the thread name which shows up in logs - vmname-lockname).

Any ideas?

### PR DESCRIPTION
**Pull request by brunotm**
This PR address the singularity of locknames, avoiding possible unnecessary waits when working with volumes with the same names in different tenants.
It also adds more functionality to the threadutils package.

Fixes #758.

### CODE REVIEW

**Comment by msterin** [comment]
The code looks good to me. I am not sure it solves a real problem as the changes of name clash  * lock contention on mgt op are extremely low IMO, but it is a better naming scheme anyways (and may help in troubleshooting). 

I am not sure how it was tested though ?

**Comment by brunotm** [comment]
@msterin 
Yes, they are low. :)
I couldn't let this pass because i've seen too many volumes named only "oracle/elk/cassandra-data" and while the majority of ops are very fast, cloning can be time consuming.

Only did basic tests. I can post more complete tests soon.

**Comment by msterin** [comment]
Basic tests log is good enough (we should not be merging without *some* info on test methods and results :-)), anything automated is even better.

**Comment by brunotm** [comment]
@msterin 
Below are tests done to trigger the waiting with both current and the code from this PR. This test bed has fast volumes and the test where made with little data.
I really couldn't think about automated tests for this one beyond regexps and log crunching, maybe in another PR :)

[1-vmdk_ops.log.gz](https://github.com/vmware/docker-volume-vsphere/files/605104/1-vmdk_ops.log.gz)
[2-vmdk_ops.log.gz](https://github.com/vmware/docker-volume-vsphere/files/605105/2-vmdk_ops.log.gz)


***volume created in tenant t1***
```
root@vsc01:~# docker volume inspect vdata@datastore1
[
    {
        "Name": "vdata@datastore1",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/vdata@datastore1",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "2GB",
                "size": "5GB"
            },
            "clone-from": "None",
            "created": "Mon Nov 21 22:30:46 2016",
            "created by VM": "vsc01",
            "datastore": "datastore1",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        },
        "Labels": {},
        "Scope": "global"
    }
]
```

***volume created in tenant t2***
```
[
    {
        "Name": "vdata",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/vdata",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "39MB",
                "size": "1GB"
            },
            "clone-from": "None",
            "created": "Mon Nov 21 23:14:19 2016",
            "created by VM": "vsc02",
            "datastore": "datastore2",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        },
        "Labels": {},
        "Scope": "global"
    }
]
```

Commands issued at same time via terminal input broadcasting.

With the code from current.
***tenant t1***
```
root@vsc01:~# time docker volume create -d vmdk --name clone -o clone-from=vdata
clone

real	0m10.121s
user	0m0.008s
sys	0m0.004s
root@vsc01:~#
```

***tenant t2***
```
root@vsc02:~# sleep 2 && time docker volume inspect vdata  > /dev/null

real	0m8.127s
user	0m0.012s
sys	0m0.000s
root@vsc02:~#
```

***Same inspect without name concurrency***
```
root@vsc02:~# time docker volume inspect vdata > /dev/null

real	0m0.021s
user	0m0.004s
sys	0m0.004s
```



With the code from this PR and the same tenant and vdata volumes:

***tenant t1***
```
root@vsc01:~# time docker volume create -d vmdk --name clone -o clone-from=vdata
clone

real	0m10.236s
user	0m0.008s
sys	0m0.004s
root@vsc01:~#
```

***tenant t2***
```
root@vsc02:~# sleep 2 && time docker volume inspect vdata  > /dev/null

real	0m0.031s
user	0m0.008s
sys	0m0.002s
root@vsc02:~#
```

**Comment by msterin** [comment]
LGTM pending conflict resolution

**Comment by brunotm** [comment]
@msterin 
I didn't see the commit to master failure. Looking at the logs it doesn't seem related to the change:

sanity_test.go:265: Parallel test failed, err: Error response from daemon: create volTestP14: VolumeDriver.Create: Failed to add disk scsi1:0.
FAIL
```
11/15/16 01:07:53 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] executeRequest 'get' completed with ret={u'Error': 'Volume volTestP14 not found (file: /vmfs/volumes/vsanDatastore/dockvols/volTestP14.vmdk)'}
11/15/16 01:07:53 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] *** createVMDK: /vmfs/volumes/vsanDatastore/dockvols/volTestP14.vmdk opts = {u'size': u'1gb', u'fstype': u'ext4'}
11/15/16 01:08:45 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [ERROR  ] Failed to create devFS node for eb5f2a58-fde9-d4b1-8d76-000c29e3609e
11/15/16 01:08:45 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] executeRequest 'create' completed with ret=None
11/15/16 01:08:47 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] *** attachVMDK: /vmfs/volumes/vsanDatastore/dockvols/volTestP14.vmdk to Ubuntu.1404.vsan VM uuid = 564dfb57-9a65-0c36-81d0-26cd117aa534
11/15/16 01:08:49 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] Attaching /vmfs/volumes/vsanDatastore/dockvols/volTestP14.vmdk as independent_persistent
11/15/16 01:08:58 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] executeRequest 'attach' completed with ret={u'Error': 'Failed to add disk scsi1:0.'}
11/15/16 01:09:01 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] *** removeVMDK: /vmfs/volumes/vsanDatastore/dockvols/volTestP14.vmdk
11/15/16 01:09:28 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] executeRequest 'remove' completed with ret=None
11/15/16 01:09:28 5892780 [Ubuntu.1404.vsan-[vsanDatastore] dockvols/volTestP14.vmdk] [INFO   ] executeRequest 'get' completed with ret={u'Error': 'Volume volTestP14 not found (file: /vmfs/volumes/vsanDatastore/dockvols/volTestP14.vmdk)'}
```

**Comment by brunotm** [comment]
The error came from vmdk_ops.get_vsan_devfs_path() which isn't logging the objtool output on error.

**Comment by msterin** [comment]
Hmm. CI passes fine before the merge.  
 /Cc @kerneltime

**Comment by brunotm** [comment]
@msterin
I have made a test PR #765 on top of master trying to reproduce and get useful logs, but the CI passed

**Pull request merged**
