### PR TITLE
Adds basic volume create impl for Windows

### PR DESCRIPTION
**Pull request by venilnoronha**
## Description

This PR adds an npipe/http endpoint for creating volumes from Windows hosts.

* Splits config.go into config_linux.go and config_windows.go files.
* Splits existing main.go plugin implementation into main_linux.go and main_windows.go files.
* Adds conditional to use vmci_client.dll via CGO in esx_vmdkcmd.go, on windows hosts.
* Adds README describing windows plugin usage.
* Adds Microsoft/go-winio vendor package.

## Test Results
`test-all` target passes locally, and following is the tail'd output.

```
	refcnt_test.go:76: 2017-06-20T14:17:16-07:00 Found: ""
	refcnt_test.go:76: 2017-06-20T14:17:16-07:00 Expected pattern: "count=5 mounted=true"
	refcnt_test.go:76: 2017-06-20T14:17:17-07:00 Found: ""
	refcnt_test.go:76: 2017-06-20T14:17:17-07:00 Expected pattern: "count=5 mounted=true"
	refcnt_test.go:76: 2017-06-20T14:17:18-07:00 Cleaning up containers
	refcnt_test.go:76: 2017-06-20T14:17:20-07:00 Checking that the volume is unmounted and can be removed
	refcnt_test.go:76: 2017-06-20T14:17:20-07:00 refCountTestVol
	refcnt_test.go:76: 2017-06-20T14:17:20-07:00 TEST PASSED.
=== RUN   TestSanity
2017-06-20T14:17:21-07:00 START: Running TestSanity on  tcp://10.192.60.198:2375 (may take a while)...
2017-06-20T14:17:36-07:00 END: Running TestSanity on  tcp://10.192.60.198:2375 (may take a while)...
--- PASS: TestSanity (14.97s)
	sanity_test.go:201: Successfully connected to tcp://10.192.60.198:2375
	sanity_test.go:201: Successfully connected to tcp://10.192.46.211:2375
	sanity_test.go:219: Creating vol=DefaultTestVol on client tcp://10.192.60.198:2375.
	sanity_test.go:105: Running cmd=&[touch /mnt/testvol/DefaultTestVol/file_to_touch] with vol=DefaultTestVol on client tcp://10.192.60.198:2375
	sanity_test.go:105: Running cmd=&[stat /mnt/testvol/DefaultTestVol/file_to_touch] with vol=DefaultTestVol on client tcp://10.192.60.198:2375
=== RUN   TestConcurrency
2017-06-20T14:17:36-07:00 Running concurrent tests on tcp://10.192.60.198:2375 and tcp://10.192.46.211:2375 (may take a while)...
2017-06-20T14:17:36-07:00 START: Running create/delete multi-host concurrent test ...
2017-06-20T14:18:00-07:00 END: Running create/delete multi-host concurrent test ...
Running same docker host concurrent create/delete test on tcp://10.192.60.198:2375...
2017-06-20T14:18:14-07:00 START: Running clone concurrent test...
2017-06-20T14:18:30-07:00 END: Running clone concurrent test...
--- PASS: TestConcurrency (54.40s)
	sanity_test.go:201: Successfully connected to tcp://10.192.60.198:2375
	sanity_test.go:201: Successfully connected to tcp://10.192.46.211:2375
PASS
coverage: 38.1% of statements
```

### CODE REVIEW

**Comment by venilnoronha** [comment]
@pshahzeb and @shaominchen have already reviewed this PR on my [private branch](https://github.com/venilnoronha/docker-volume-vsphere/pull/2), and it is ready for merging.

**Comment by shaominchen** [comment]
Can we split this PR into multiples for easier tracking purpose? At least we can split it into 2: one for all dependent files, and the other for new code that we implemented.

**Comment by pdhamdhere** [comment]
Yes, please put censoring in separate PR.

**Comment by venilnoronha** [comment]
Sure. I'm closing this PR for now. Will reopen another one once I have the vendor code merged.

**Pull request closed without merging**
