### PR TITLE
kv/disklib thread investigation.

### PR DESCRIPTION
**Pull request by brunotm**
This PR is intended to gather data and investigate about possibly and uncontrolled concurrent operations on same volumes metadata. Not for merging.

It will serialize and log intentions and waits for locks of kv calls with their arguments.

The topic is being discussed on #695, #662, #626 and possibly other closed issues.

### CODE REVIEW

**Comment by msterin** [comment]
Actually, DiskLib is *not* thread-safe so this PR is a prime candidate for merge. The fix looks good though  I think the locks should be lower, in kvESX.py

//CC @govint

**Comment by brunotm** [comment]
@msterin thank you! :)
The first approach was on kvESX, but as the interfaces where all exposed and used by volume_kv I moved it there. 
I will adjust and push.

**Comment by msterin** [comment]
@brunotm - actually the more accurate statement about disklib is "Can't use the same handle in multiple threads, but you can use different handles in multiple threads". Basically, `dhandle` is not protected and not thread-safe, but the rest is

**Comment by brunotm** [comment]
@msterin 
This seems odd. The dhandles are created inside the thread context in kvESX.vol_open_path and passed to disklib, i am missing something? :)

Pushed a change to explicitly keep in TLS the ctypes passed as pointers to disklib, but i'm not sure if placing the locks in the kvESX.create/delete/load/save/get_info/disk_lib_init and making everything else _private wouldn't be safer.

**Comment by brunotm** [comment]
Closed in favor of #708

**Comment by msterin** [comment]
@brunotm 
> This seems odd. The dhandles are created inside the request thread context in kvESX.vol_open_path and passed to disklib (that is loaded in the MainThread context and shared), i am missing something? :)

No, I do not think you do. dhandles are not thread safe **within** disklib - they structures backing them are not protected - but as long as dhandles are per-thread, there is no issues here. I slightly overreacted.

> Pushed a change to explicitly keep in TLS the ctypes passed as pointers to disklib, but i'm not sure if placing the locks in the kvESX.create/delete/load/save/get_info/disk_lib_init and making everything else _private, or yet, protect everything with a reentrant lock and keep as is wouldn't be safer.

As I said, I overreacted. As long as dhandles are not crossing thread boundaries, disklib is thread safe.

> what do you think?
Unfortunately, nothing. I will be looking into the code this coming week - had totally other (non-code :-)) priorities the past week.
what do you think?

**Pull request closed without merging**
