### PR TITLE
Fix for the broken images on docs site

### PR DESCRIPTION
**Pull request by vishal-biyani**

### CODE REVIEW

**Comment by shuklanirdesh82** [comment]
@vishal-biyani images are not available... do we need to perform any step?

**Comment by vishal-biyani** [comment]
@shuklanirdesh82 I think the Docker cert image is still not loading in Documentation, I was just checking too. Let me take a quick look and fix right away

**Comment by shuklanirdesh82** [comment]
One more thing .. "edit me" link is broken too ... I guess the last merge regarding k8s doc merge might have broken this. What do you think?

**Comment by girishshilamkar** [comment]
@shuklanirdesh82 k8s doc merge is independent so shouldn't affect. I am yet to land in SJ ... will get started as soon as I get stable internet connection.

**Pull request merged**
