### PR TITLE
Support vol stats

### PR DESCRIPTION
**Pull request by govint**
Added support for volumes stats on Get(). The change to go-plugin-helpers is only to allow building and returning volume stats. I've opened an issue on go-plugin-helpers to add this support (issue 53). I've made changes for that and will post a separate PR on go-plugin-helpers once I'm added to the members  list there.

Will pull in the updated go-plugin-helpers once volume status is supported there.

### CODE REVIEW

**Comment by pdhamdhere** [comment]
Can you please include sample output for attached and detached volume in PR description?

**Comment by govint** [comment]
Yes, Will do.

**Comment by govint** [comment]
Testing with the patch we have the status reported as shown:

$ docker volume create --driver=vmdk --name=dvol_2
dvol_2

$ docker volume inspect dvol_2
[
    {
        "Name": "dvol_2",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/dvol_2",
        "Status": {
            "capacity": {
                "allocated": "14.0MB",
                "size": "100.0MB"
            },
            "created": "Tue Jul 26 05:04:56 2016",
            "created-by": "2",
            "datastore": "bigone",
            "status": "detached"
        },
        "Labels": {},
        "Scope": "global"
    }
]
$ docker run --rm -it -v dvol_2:/mnt/myvol busybox
/ #


Status now shows the volume as attached and the VM to which attached.

$ docker volume inspect dvol_2
[
    {
        "Name": "dvol_2",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/dvol_2",
        "Status": {
            "attachedVMName": "2",
            "capacity": {
                "allocated": "14.0MB",
                "size": "100.0MB"
            },
            "created": "Tue Jul 26 05:04:56 2016",
            "created-by": "2",
            "datastore": "bigone",
            "status": "attached"
        },
        "Labels": {},
        "Scope": "global"
    }
]

**Comment by kerneltime** [comment]
Can you link the PR for the helper that you posted?

**Comment by msterin** [comment]
Overall looks good - with 1 nit and one issue, specifically - please add (automated) test or two, and it's GTM after that.

**Comment by govint** [comment]
Mark,
    Yes I will submit this once the change to the helpers is submitted.

**Comment by govint** [comment]
Change to plugin helpers - https://github.com/docker/go-plugins-helpers/pull/54

**Comment by pdhamdhere** [comment]
@govint Rebase and merge?

**Comment by govint** [comment]
Prashant, yes I'll do that.

On Thu, Aug 4, 2016 at 8:13 AM, Prashant Dhamdhere <notifications@github.com

**Pull request merged**
